# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - rules/*.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
    - targets: ['appserver.automi.local:9308']

  - job_name: 'Nodes'
    scrape_interval: 5s
    static_configs:
      - targets: ['appserver.automi.local:9100','bastion.automi.local:9100','infra.automi.local:9100' ]
